spring:
  application:
    name: springboot_example
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306
    username: root
    password: "040428"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

# HTTP服务器端口配置
http:
  port: 8080

# 服务器配置
server:
  # HTTPS服务端口配置
  port: 444
  ssl:
    # SSL密钥库文件路径
    key-store: classpath:https.keystore
    # 密钥库中的别名
    key-alias: tomcat
    # 是否启用SSL
    enabled: true
    # 密钥库密码
    key-store-password: 123456
    # 密钥库类型（Java KeyStore）
    key-store-type: JKS


#显示sql语句

