server:
  ssl:
    key-store: classpath:keystore.jks
    key-password: 123456
    key-store-type: JKS
    key-alias: tomcat
#    enabled: true
#    protocol: TLS
  port: 444

spring:
  application:
    name: springboot_example
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/software_structure
    username: root
    password: "040428"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

#显示sql语句

